### PR TITLE
solution

### PR DESCRIPTION
**Pull request by anujpuri72**
just another solution :)

### CODE REVIEW

**Comment by anujpuri72** [comment]
we have to show the last modified time that is in the output of ./semester cmd

**Comment by anujpuri72** [comment]
@thepushkarp  PTAL

**Comment by thepushkarp** [comment]
Yeah, this was what we needed to do. Thanks! :smiley:

**Comment by thepushkarp** [comment]
Sorry, didn't saw the notification earlier.

**Pull request merged**
